export { crearCartaHTML } from './crear-carta'
export { crearDeck } from './crear-deck'
export { pedirCarta } from './pedir-carta'
export { turnoComputador } from './turno-computadora'
export { valorCarta } from './valor-carta'